kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: claim-postgres
spec:
  storageClassName: ''
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: pv0001
